name: Build image Dockerfile

on: [push, pull_request]

#Global variables
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DH_TOKEN: ${{ secrets.DH_TOKEN }}
  DH_REPOSITORY: ${{ secrets.DH_REPOSITORY }}
  WP_HOST: ${{ secrets.WP_HOST }}
  WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  WP_PREFIX: ${{ secrets.WP_PREFIX }}
  DB_USER: ${{ secrets.DB_USER }}
  
jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login DockerHub
        run: |
          docker login -u $DOCKER_USER -p $DH_TOKEN

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: aureliosmalheiros/wordpress-testing:0.7
          build-args: |
            WP_HOST=${{ secrets.WP_HOST }}
            WP_PASSWORD=${{ secrets.WP_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            WP_PREFIX=${{ secrets.WP_PREFIX }}
            DB_USER=${{ secrets.DB_USER }}